import { useState } from 'react';
import { ArrowUpRight, ArrowRight, Download, Menu, X, FileText, Award, Cloud, Layers, Network, Terminal, Mail, Github, Linkedin, ChevronRight, Code2 } from 'lucide-react';
import { SiPython, SiCplusplus, SiJavascript, SiReact, SiNodedotjs, SiDocker, SiKubernetes, SiGitlab, SiMongodb, SiMysql, SiBootstrap, SiScikitlearn, SiLeetcode, SiLinux } from 'react-icons/si';
import { Button } from '@/components/ui/button';
import BlurText from './BlurText';
import resume from '@/assets/resume.asset.json';
import activity from '@/assets/activity.json';

const links = { github: 'https://github.com/mohammed123-code', linkedin: 'https://www.linkedin.com/in/santhu-mohammed-m-490509328/', leetcode: 'https://leetcode.com/u/mohammedcode-123/', email: 'santhumohammed.m2024aiml@sece.ac.in' };
const projects = [
  { title: 'Cloud Infrastructure & AWS Automation', category: 'AWS · CLOUD INFRASTRUCTURE', icon: Cloud, description: 'Hands-on cloud infrastructure using EC2, S3, VPC, Route 53 and Auto Scaling. Configured security groups and followed deployment and monitoring best practices.', stack: ['AWS', 'Linux', 'EC2', 'VPC'], status: 'Ongoing', detail: 'Implemented core AWS services and configured cloud environments with a focus on reliable deployment, access controls and monitoring.' },
  { title: 'Spotify DevOps Platform', category: 'CI/CD · CONTAINER ORCHESTRATION', icon: SiDocker, description: 'A Spotify-inspired application, containerized with Docker and deployed on Kubernetes. GitLab CI/CD automates build, testing and deployment workflows.', stack: ['Docker', 'K3s', 'GitLab CI/CD', 'AWS'], status: '2026', detail: 'Worked with Docker images, Kubernetes (K3s) orchestration and GitLab pipelines to automate the application delivery lifecycle on AWS and Linux.' },
  { title: 'Crop Yield Prediction System', category: 'MACHINE LEARNING · AGRICULTURE', icon: SiPython, description: 'Predicting crop yield from agricultural and environmental data. An interactive Streamlit application brings predictions and data visualization together.', stack: ['Python', 'Scikit-learn', 'Pandas', 'Streamlit'], status: '2026', detail: 'Developed a machine learning model using agricultural and environmental datasets, and built an interactive Streamlit interface for predictions and visualization.' },
];
const skills = [ ['Python', SiPython], ['C / C++', SiCplusplus], ['Java', Code2], ['JavaScript', SiJavascript], ['React', SiReact], ['Node.js', SiNodedotjs], ['AWS', Cloud], ['Docker', SiDocker], ['Kubernetes', SiKubernetes], ['GitLab CI/CD', SiGitlab], ['MongoDB', SiMongodb], ['MySQL', SiMysql], ['Bootstrap', SiBootstrap], ['Scikit-learn', SiScikitlearn], ['Linux', SiLinux] ] as const;
const certificates = [ { title: 'Networking Basics', issuer: 'Cisco', year: '2026', url: '' }, { title: 'C & C++ Training', issuer: 'IIT Bombay', year: '2025', url: '' }, { title: 'C++ · Python · Java', issuer: 'SkillRack', year: '2025', url: '' }, { title: 'HTML, CSS & JS Essential Training', issuer: 'LinkedIn Learning', year: '2024', url: '' } ];
const nav = [['work','Work'],['skills','Skills'],['lc','LeetCode'],['certs','Certificates'],['contact','Contact']];
function Label({ children, code }: { children: React.ReactNode; code: string }) { return <h2 className="section-label">{children}<span>({code})</span></h2>; }
function External({ href, children, className = '' }: { href: string; children: React.ReactNode; className?: string }) { return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>; }
export default function Portfolio() {
 const [menu, setMenu] = useState(false);
 const [selected, setSelected] = useState<number | null>(null);
 return <div className="min-h-screen bg-background text-foreground font-display antialiased">
  <nav aria-label="Main navigation" className="sticky top-0 z-30 border-b border-border bg-background/95 backdrop-blur-md">
   <div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-6 py-4">
    <a href="#top" className="flex items-center gap-3 font-mono text-[11px] uppercase"><span className="status-dot"/><span>Santhu Mohammed M<span className="text-primary">.</span></span></a>
    <div className="hidden md:flex gap-7 font-mono text-[11px] text-muted-foreground uppercase">{nav.map(([id,title]) => <a key={id} href={`#${id}`} className="hover:text-primary transition-colors">{title}</a>)}</div>
    <div className="flex gap-2"><Button variant="outline" size="sm" className="font-mono text-primary border-primary/35 hover:bg-primary/10 hover:text-primary" asChild><a href={resume.url} target="_blank" rel="noopener noreferrer"><Download/>resume.pdf</a></Button><Button variant="ghost" size="icon" className="md:hidden" aria-label={menu ? 'Close navigation' : 'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu ? <X/> : <Menu/>}</Button></div>
   </div>
   {menu && <div className="flex flex-wrap gap-5 border-t border-border px-6 py-4 font-mono text-xs md:hidden">{nav.map(([id,title])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{title}</a>)}</div>}
  </nav>
  <header id="top" className="relative overflow-hidden border-b border-border">
   <div className="site-grid hero-grid"/>
   <div className="relative mx-auto grid max-w-6xl grid-cols-1 gap-10 px-6 pt-20 pb-16 lg:grid-cols-12 items-end">
    <div className="lg:col-span-7">
     <p className="font-mono text-[11px] text-primary uppercase mb-6">ML / Cloud–DevOps / Full-stack</p>
     <h1 aria-label="Santhu Mohammed M" className="text-[48px] sm:text-6xl md:text-7xl font-bold leading-[1.02]"><BlurText text="Santhu" delay={75} stepDuration={.2}/><BlurText text="Mohammed M" delay={75} stepDuration={.2}/></h1>
     <p className="mt-6 max-w-[46ch] text-[15px] leading-relaxed text-muted-foreground">AI/ML undergraduate engineering systems where models meet infrastructure — cloud deployments, automated pipelines, and full-stack applications.</p>
     <div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-10 rounded-lg px-5"><a href="#work">View work<ArrowRight/></a></Button><Button asChild variant="outline" className="h-10 rounded-lg px-5"><a href="#contact">Get in touch<ArrowUpRight/></a></Button></div>
    </div>
    <div className="lg:col-span-5"><div className="topology">
     <div className="flex justify-between border-b border-border pb-3 mb-3"><span className="text-primary">// engineering stack</span><span className="text-muted-foreground">01 — 03</span></div>
     <div className="topology-row"><SiReact/><span>interface / react</span><span className="ml-auto text-primary">01</span></div>
     <div className="topology-branch"><div className="topology-row"><Network/><span>api / node · express</span></div><div className="topology-branch"><div className="topology-row"><SiPython/><span>model / scikit-learn</span></div><div className="topology-row"><SiMongodb/><span>data / mongodb · mysql</span></div></div></div>
     <div className="pipeline-line"/>
     <div className="topology-row"><SiDocker/><span>delivery / docker · k3s</span><span className="ml-auto text-primary">02</span></div>
     <div className="topology-branch"><div className="topology-row"><SiGitlab/><span>pipeline / gitlab ci/cd</span></div><div className="topology-row"><Cloud/><span>cloud / aws · ec2 · s3</span></div></div>
     <div className="mt-4 border-t border-border pt-3 flex justify-between"><span>BE / AI & ML</span><span className="text-primary">2024 — 2028</span></div>
    </div></div>
   </div>
  </header>
  <main>
  <section id="work" className="mx-auto max-w-6xl px-6 py-16 border-b border-border"><Label code="a">Selected work</Label>
   <div className="grid grid-cols-1 md:grid-cols-3 gap-5">{projects.map((p,i)=><article key={p.title} className="project-card group"><div className="flex items-center justify-between mb-6"><p.icon className="size-7 text-signal"/><span className="font-mono text-[10px] text-muted-foreground">0{i+1} / 2026</span></div><p className="font-mono text-[10px] text-primary mb-3">{p.category}</p><h3 className="text-lg font-bold mb-3 leading-snug">{p.title}</h3><p className="text-[13px] text-muted-foreground leading-relaxed flex-1">{p.description}</p><p className="mt-5 text-[10px] font-mono text-muted-foreground">{p.stack.join(' / ')}</p><div className="mt-5 pt-4 border-t border-border flex justify-between items-center"><span className="font-mono text-[10px] text-muted-foreground">{p.status==='Ongoing' ? '● ongoing' : 'project · 2026'}</span><Button variant="ghost" size="icon" title={`View ${p.title}`} aria-label={`View ${p.title}`} onClick={()=>setSelected(i)} className="text-primary hover:bg-primary/10 hover:text-primary"><ArrowUpRight/></Button></div></article>)}</div>
  </section>
  <section id="skills" className="mx-auto max-w-6xl px-6 py-14 border-b border-border"><Label code="b">The stack</Label><div className="flex flex-wrap gap-2.5">{skills.map(([name,Icon])=><span key={name} className="flex items-center gap-2.5 px-3 py-2 border border-border rounded-md font-mono text-xs"><Icon className="skill-logo"/>{name}</span>)}</div><p className="mt-5 font-mono text-[11px] text-muted-foreground">Foundations / Data structures & algorithms · OOP · REST APIs</p></section>
  <section id="lc" className="mx-auto max-w-6xl px-6 py-14 border-b border-border grid grid-cols-1 lg:grid-cols-12 gap-8">
   <div className="lg:col-span-4"><Label code="c">LeetCode</Label><SiLeetcode className="text-amber size-8 mb-5"/><h3 className="text-2xl font-bold mb-3">One day. One more problem.</h3><p className="text-sm text-muted-foreground leading-relaxed">Daily practice, a lot of green, and a commitment to getting better.</p><External href={links.leetcode} className="mt-5 inline-flex items-center gap-2 text-xs font-mono text-primary">mohammedcode-123<ArrowUpRight className="size-4"/></External><p className="mt-4 font-mono text-[10px] text-muted-foreground">Profile snapshot · October 2026</p></div>
   <div className="lg:col-span-8"><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6">{[['453','Problems solved'],['1,564','Contest rating'],['47','Contests'],['164','Max streak / days']].map(([n,t])=><div key={t} className="border border-border rounded-lg p-4"><div className="font-mono text-2xl text-primary">{n}</div><div className="font-mono text-[9px] uppercase text-muted-foreground mt-2">{t}</div></div>)}</div><div className="flex justify-between gap-2 text-[10px] font-mono text-muted-foreground mb-4"><span><span className="text-foreground">918</span> submissions / past year</span><span><span className="text-foreground">364</span> active days</span></div><div className="heatmap" role="img" aria-label="Green activity grid recreated from the provided LeetCode screenshot">{activity.map((level,i)=><span key={i} className={`heat-cell heat-${level}`}/>)}</div><div className="mt-3 flex justify-between font-mono text-[9px] text-muted-foreground">{['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'].map(m=><span key={m}>{m}</span>)}</div><p className="mt-5 font-mono text-[10px] text-muted-foreground">237 easy · 193 medium · 23 hard <span className="text-primary">/</span> 6 badges · 365 Days Badge</p></div>
  </section>
  <section id="certs" className="mx-auto max-w-6xl px-6 py-14 border-b border-border"><Label code="d">Certifications</Label><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{certificates.map(c=><article key={c.issuer} className="flex items-center gap-4 border border-border rounded-lg p-5"><div className="certificate-slot"><FileText className="size-5"/></div><div className="flex-1 min-w-0"><p className="font-mono text-[10px] text-signal mb-1">{c.issuer} / {c.year}</p><h3 className="text-sm font-medium">{c.title}</h3>{c.url ? <External href={c.url} className="text-xs text-primary">View certificate ↗</External> : <span className="inline-block mt-2 font-mono text-[9px] text-muted-foreground">Document coming soon</span>}</div><Award className="size-5 text-muted-foreground shrink-0"/></article>)}</div></section>
  <section id="experience" className="mx-auto max-w-6xl px-6 py-14 border-b border-border"><Label code="e">Experience & education</Label><div className="row gy-5"><div className="col-12 col-md-7">{[['DevOps & SRE Intern','VSphere Technologies','2026','Docker, Kubernetes (K3s), GitLab CI/CD, Linux and virtual machines. Assisted with deployment automation and container orchestration.'],['MERN Stack Developer Intern','Better Tomorrow','2026','Full-stack applications, REST APIs and authentication modules using MongoDB, Express, React and Node.js; deployment on AWS.'],['Remote Sensing with GIS Intern','Indian Space Academy','2025','Satellite imagery, spatial data, geospatial analysis and mapping applications.']].map(([role,company,year,desc])=><article key={company} className="mb-7 pl-5 border-l border-border"><div className="flex justify-between gap-3"><h3 className="text-sm font-semibold">{role}</h3><span className="font-mono text-[10px] text-muted-foreground">{year}</span></div><p className="text-xs text-primary mt-1">{company}</p><p className="text-xs leading-relaxed text-muted-foreground mt-3 max-w-lg">{desc}</p></article>)}</div><div className="col-12 col-md-5"><div className="pl-5 border-l border-border"><p className="font-mono text-[10px] text-signal mb-3">2024 — 2028</p><h3 className="font-semibold text-lg">BE · Artificial Intelligence<br/>& Machine Learning</h3><p className="mt-2 text-sm text-muted-foreground">Sri Eshwar College of Engineering</p><p className="mt-3 font-mono text-xs text-primary">CGPA 7.94 / V semester</p><div className="mt-8 border-t border-border pt-5"><p className="font-mono text-[10px] text-muted-foreground mb-3">ACHIEVEMENTS / 2025</p><p className="text-xs leading-relaxed">Freshathon 2K25 · Third place, Project Expo 3.0</p><p className="text-xs leading-relaxed mt-3">Smart India Hackathon · Second-round qualifier</p></div></div></div></div></section>
  <section id="contact" className="mx-auto max-w-6xl px-6 py-16"><div className="relative site-grid border border-border rounded-lg p-7 md:p-10"><div className="relative flex flex-col md:flex-row md:items-end md:justify-between gap-7"><div className="min-w-0"><Label code="f">Contact</Label><h2 className="text-3xl font-bold">Let's build something meaningful.</h2><a href={`mailto:${links.email}`} className="mt-4 block text-sm text-muted-foreground break-all hover:text-primary">{links.email}</a><div className="flex gap-2 mt-5">{[[links.github,Github,'GitHub'],[links.linkedin,Linkedin,'LinkedIn'],[`mailto:${links.email}`,Mail,'Email']].map(([href,Icon,title])=>{const I=Icon as typeof Github;return <Button key={title as string} variant="outline" size="icon" asChild><a href={href as string} title={title as string} aria-label={title as string} target="_blank" rel="noopener noreferrer"><I/></a></Button>})}</div></div><div className="flex flex-col gap-3 shrink-0"><Button asChild className="h-10"><a href={resume.url} target="_blank" rel="noopener noreferrer"><Download/>Download resume</a></Button><Button asChild variant="outline" className="h-10"><External href={links.leetcode}>LeetCode profile<ArrowUpRight/></External></Button></div></div></div><footer className="mt-8 flex flex-wrap justify-between gap-3 font-mono text-[10px] text-muted-foreground"><span>© 2026 Santhu Mohammed M</span><span>AI / ML · Cloud / DevOps · Full-stack</span></footer></section>
  </main>
  {selected !== null && <div className="fixed inset-0 z-50 bg-background/90 backdrop-blur-sm flex items-center justify-center p-5" onClick={()=>setSelected(null)}><section role="dialog" aria-modal="true" aria-labelledby="project-title" className="relative max-w-xl w-full rounded-lg border border-border bg-secondary p-7" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null)}}><Button variant="ghost" size="icon" className="absolute right-3 top-3" aria-label="Close project" autoFocus onClick={()=>setSelected(null)}><X/></Button><p className="font-mono text-xs text-primary mt-3">PROJECT / 2026</p><h2 id="project-title" className="text-2xl font-bold mt-4 pr-6">{projects[selected]?.title}</h2><p className="text-sm text-muted-foreground leading-relaxed mt-5">{projects[selected]?.detail}</p><p className="text-xs font-mono mt-6 text-signal">{projects[selected]?.stack.join(' / ')}</p><Button asChild variant="outline" className="mt-7"><External href={links.github}><Github/>View GitHub profile<ChevronRight/></External></Button></section></div>}
 </div>;
}
